server:
  port: 8082

spring:
  application:
    name: activity-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

logging:
  level:
    root: warn
    com.pdereg.timelogger: info