version: '2'

services:
  api-gateway:
    image: api-gateway
    ports:
      - "80:8080"
    environment:
      - EUREKA_HOST=discovery-server
      - TIME_LOGGER_SECRET=${TIME_LOGGER_SECRET}
    depends_on:
      - discovery-server
  discovery-server:
    image: discovery-server
    ports:
      - "8761:8761"
  account-service:
    image: account-service
    environment:
      - MONGODB_HOST=account-database
      - EUREKA_HOST=discovery-server
      - TIME_LOGGER_SECRET=${TIME_LOGGER_SECRET}
    depends_on:
      - discovery-server
      - account-database
  account-database:
    image: mongo
  activity-service:
    image: activity-service
    environment:
      - MONGODB_HOST=activity-database
      - EUREKA_HOST=discovery-server
      - TIME_LOGGER_SECRET=${TIME_LOGGER_SECRET}
    depends_on:
      - discovery-server
      - activity-database
  activity-database:
    image: mongo
