server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

zuul:
  routes:
    accounts:
      path: /api/accounts/**
      serviceId: account-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    activities:
      path: /api/activities/**
      serviceId: activity-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    logs:
      path: /api/logs/**
      serviceId: log-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie

logging:
  level:
    root: warn
    com.pdereg.timelogger: info