server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

zuul:
  routes:
    accounts:
      path: /api/accounts/**
      serviceId: account-service
      stripPrefix: false
