server:
  port: 8084

spring:
  application:
    name: log-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

logging:
  level:
    root: warn
    com.pdereg.timelogger: info