server:
  port: 8081

spring:
  application:
    name: account-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
